// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'site_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_WebSite _$WebSiteFromJson(Map<String, dynamic> json) => _WebSite(
  url:
      (json['url'] as List<dynamic>?)?.map((e) => e as String).toList() ??
      const [],
  name: json['name'] as String? ?? '',
  nickname: json['nickname'] as String? ?? '',
  logo: json['logo'] as String? ?? '',
  tracker: json['tracker'] as String? ?? '',
  spFull: (json['sp_full'] as num?)?.toInt() ?? 0,
  limitSpeed: (json['limit_speed'] as num?)?.toInt() ?? 0,
  tags: json['tags'] as String? ?? '',
  iyuu: (json['iyuu'] as num?)?.toInt() ?? 0,
  signIn: json['sign_in'] as bool? ?? false,
  getInfo: json['get_info'] as bool? ?? false,
  repeatTorrents: json['repeat_torrents'] as bool? ?? false,
  brushFree: json['brush_free'] as bool? ?? false,
  brushRss: json['brush_rss'] as bool? ?? false,
  hrDiscern: json['hr_discern'] as bool? ?? false,
  searchTorrents: json['search_torrents'] as bool? ?? false,
  pageIndex: json['page_index'] as String? ?? '',
  pageTorrents: json['page_torrents'] as String? ?? '',
  pageSignIn: json['page_sign_in'] as String? ?? '',
  pageControlPanel: json['page_control_panel'] as String? ?? '',
  pageDetail: json['page_detail'] as String? ?? '',
  pageDownload: json['page_download'] as String? ?? '',
  pageUser: json['page_user'] as String? ?? '',
  pageSearch: json['page_search'] == null
      ? const []
      : _stringListFromJson(json['page_search']),
  pageMessage: json['page_message'] as String? ?? '',
  pageHr: json['page_hr'] as String? ?? '',
  pageLeeching: json['page_leeching'] as String? ?? '',
  pageUploaded: json['page_uploaded'] as String? ?? '',
  pageSeeding: json['page_seeding'] as String? ?? '',
  pageCompleted: json['page_completed'] as String? ?? '',
  pageMybonus: json['page_mybonus'] as String? ?? '',
  pageViewfilelist: json['page_viewfilelist'] as String? ?? '',
  signInfoTitle: json['sign_info_title'] as String? ?? '',
  signInfoContent: json['sign_info_content'] as String? ?? '',
  hr: json['hr'] as bool? ?? false,
  hrRate: (json['hr_rate'] as num?)?.toInt() ?? 0,
  hrTime: (json['hr_time'] as num?)?.toInt() ?? 0,
  myInvitationRule: json['my_invitation_rule'] as String? ?? '',
  myTimeJoinRule: json['my_time_join_rule'] as String? ?? '',
  myLatestActiveRule: json['my_latest_active_rule'] as String? ?? '',
  myUploadedRule: json['my_uploaded_rule'] as String? ?? '',
  myDownloadedRule: json['my_downloaded_rule'] as String? ?? '',
  myRatioRule: json['my_ratio_rule'] as String? ?? '',
  myBonusRule: json['my_bonus_rule'] as String? ?? '',
  myPerHourBonusRule: json['my_per_hour_bonus_rule'] as String? ?? '',
  myScoreRule: json['my_score_rule'] as String? ?? '',
  myLevelRule: json['my_level_rule'] as String? ?? '',
  myPasskeyRule: json['my_passkey_rule'] as String? ?? '',
  myUidRule: json['my_uid_rule'] as String? ?? '',
  myHrRule: json['my_hr_rule'] as String? ?? '',
  myLeechRule: json['my_leech_rule'] as String? ?? '',
  myPublishRule: json['my_publish_rule'] as String? ?? '',
  mySeedRule: json['my_seed_rule'] as String? ?? '',
  mySeedVolRule: json['my_seed_vol_rule'] as String? ?? '',
  myMailboxRule: json['my_mailbox_rule'] as String? ?? '',
  myMessageTitle: json['my_message_title'] as String? ?? '',
  myNoticeRule: json['my_notice_rule'] as String? ?? '',
  myNoticeTitle: json['my_notice_title'] as String? ?? '',
  myNoticeContent: json['my_notice_content'] as String? ?? '',
  torrentsRule: json['torrents_rule'] as String? ?? '',
  torrentTitleRule: json['torrent_title_rule'] as String? ?? '',
  torrentSubtitleRule: json['torrent_subtitle_rule'] as String? ?? '',
  torrentDetailUrlRule: json['torrent_detail_url_rule'] as String? ?? '',
  torrentCategoryRule: json['torrent_category_rule'] as String? ?? '',
  torrentPosterRule: json['torrent_poster_rule'] as String? ?? '',
  torrentMagnetUrlRule: json['torrent_magnet_url_rule'] as String? ?? '',
  torrentSizeRule: json['torrent_size_rule'] as String? ?? '',
  torrentProgressRule: json['torrent_progress_rule'] as String? ?? '',
  torrentHrRule: json['torrent_hr_rule'] as String? ?? '',
  torrentSaleRule: json['torrent_sale_rule'] as String? ?? '',
  torrentSaleExpireRule: json['torrent_sale_expire_rule'] as String? ?? '',
  torrentReleaseRule: json['torrent_release_rule'] as String? ?? '',
  torrentSeedersRule: json['torrent_seeders_rule'] as String? ?? '',
  torrentLeechersRule: json['torrent_leechers_rule'] as String? ?? '',
  torrentCompletersRule: json['torrent_completers_rule'] as String? ?? '',
  torrentTagsRule: json['torrent_tags_rule'] as String? ?? '',
  detailTitleRule: json['detail_title_rule'] as String? ?? '',
  detailSubtitleRule: json['detail_subtitle_rule'] as String? ?? '',
  detailDownloadUrlRule: json['detail_download_url_rule'] as String? ?? '',
  detailSizeRule: json['detail_size_rule'] as String? ?? '',
  detailCategoryRule: json['detail_category_rule'] as String? ?? '',
  detailCountFilesRule: json['detail_count_files_rule'] as String? ?? '',
  detailHashRule: json['detail_hash_rule'] as String? ?? '',
  detailFreeRule: json['detail_free_rule'] as String? ?? '',
  detailFreeExpireRule: json['detail_free_expire_rule'] as String? ?? '',
  detailDoubanRule: json['detail_douban_rule'] as String? ?? '',
  detailImdbRule: json['detail_imdb_rule'] as String? ?? '',
  detailPosterRule: json['detail_poster_rule'] as String? ?? '',
  detailTagsRule: json['detail_tags_rule'] as String? ?? '',
  detailHrRule: json['detail_hr_rule'] as String? ?? '',
  alive: json['alive'] as bool? ?? false,
  pagePiecesHashApi: json['page_pieces_hash_api'] as String? ?? '',
  piecesRepeat: json['pieces_repeat'] as bool? ?? false,
  proxy: json['proxy'] as bool? ?? false,
  structure: json['structure'] as String? ?? '',
  type: json['type'] as String? ?? '',
  nation: json['nation'] as String? ?? '',
  myEmailRule: json['my_email_rule'] as String? ?? '',
  myUsernameRule: json['my_username_rule'] as String? ?? '',
  buyPage: json['buy_page'] as String? ?? '',
  buyAction:
      (json['buy_action'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(k, e as String),
      ) ??
      const {},
  level:
      (json['level'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(k, SiteLevel.fromJson(e as Map<String, dynamic>)),
      ) ??
      const {},
);

Map<String, dynamic> _$WebSiteToJson(_WebSite instance) => <String, dynamic>{
  'url': instance.url,
  'name': instance.name,
  'nickname': instance.nickname,
  'logo': instance.logo,
  'tracker': instance.tracker,
  'sp_full': instance.spFull,
  'limit_speed': instance.limitSpeed,
  'tags': instance.tags,
  'iyuu': instance.iyuu,
  'sign_in': instance.signIn,
  'get_info': instance.getInfo,
  'repeat_torrents': instance.repeatTorrents,
  'brush_free': instance.brushFree,
  'brush_rss': instance.brushRss,
  'hr_discern': instance.hrDiscern,
  'search_torrents': instance.searchTorrents,
  'page_index': instance.pageIndex,
  'page_torrents': instance.pageTorrents,
  'page_sign_in': instance.pageSignIn,
  'page_control_panel': instance.pageControlPanel,
  'page_detail': instance.pageDetail,
  'page_download': instance.pageDownload,
  'page_user': instance.pageUser,
  'page_search': instance.pageSearch,
  'page_message': instance.pageMessage,
  'page_hr': instance.pageHr,
  'page_leeching': instance.pageLeeching,
  'page_uploaded': instance.pageUploaded,
  'page_seeding': instance.pageSeeding,
  'page_completed': instance.pageCompleted,
  'page_mybonus': instance.pageMybonus,
  'page_viewfilelist': instance.pageViewfilelist,
  'sign_info_title': instance.signInfoTitle,
  'sign_info_content': instance.signInfoContent,
  'hr': instance.hr,
  'hr_rate': instance.hrRate,
  'hr_time': instance.hrTime,
  'my_invitation_rule': instance.myInvitationRule,
  'my_time_join_rule': instance.myTimeJoinRule,
  'my_latest_active_rule': instance.myLatestActiveRule,
  'my_uploaded_rule': instance.myUploadedRule,
  'my_downloaded_rule': instance.myDownloadedRule,
  'my_ratio_rule': instance.myRatioRule,
  'my_bonus_rule': instance.myBonusRule,
  'my_per_hour_bonus_rule': instance.myPerHourBonusRule,
  'my_score_rule': instance.myScoreRule,
  'my_level_rule': instance.myLevelRule,
  'my_passkey_rule': instance.myPasskeyRule,
  'my_uid_rule': instance.myUidRule,
  'my_hr_rule': instance.myHrRule,
  'my_leech_rule': instance.myLeechRule,
  'my_publish_rule': instance.myPublishRule,
  'my_seed_rule': instance.mySeedRule,
  'my_seed_vol_rule': instance.mySeedVolRule,
  'my_mailbox_rule': instance.myMailboxRule,
  'my_message_title': instance.myMessageTitle,
  'my_notice_rule': instance.myNoticeRule,
  'my_notice_title': instance.myNoticeTitle,
  'my_notice_content': instance.myNoticeContent,
  'torrents_rule': instance.torrentsRule,
  'torrent_title_rule': instance.torrentTitleRule,
  'torrent_subtitle_rule': instance.torrentSubtitleRule,
  'torrent_detail_url_rule': instance.torrentDetailUrlRule,
  'torrent_category_rule': instance.torrentCategoryRule,
  'torrent_poster_rule': instance.torrentPosterRule,
  'torrent_magnet_url_rule': instance.torrentMagnetUrlRule,
  'torrent_size_rule': instance.torrentSizeRule,
  'torrent_progress_rule': instance.torrentProgressRule,
  'torrent_hr_rule': instance.torrentHrRule,
  'torrent_sale_rule': instance.torrentSaleRule,
  'torrent_sale_expire_rule': instance.torrentSaleExpireRule,
  'torrent_release_rule': instance.torrentReleaseRule,
  'torrent_seeders_rule': instance.torrentSeedersRule,
  'torrent_leechers_rule': instance.torrentLeechersRule,
  'torrent_completers_rule': instance.torrentCompletersRule,
  'torrent_tags_rule': instance.torrentTagsRule,
  'detail_title_rule': instance.detailTitleRule,
  'detail_subtitle_rule': instance.detailSubtitleRule,
  'detail_download_url_rule': instance.detailDownloadUrlRule,
  'detail_size_rule': instance.detailSizeRule,
  'detail_category_rule': instance.detailCategoryRule,
  'detail_count_files_rule': instance.detailCountFilesRule,
  'detail_hash_rule': instance.detailHashRule,
  'detail_free_rule': instance.detailFreeRule,
  'detail_free_expire_rule': instance.detailFreeExpireRule,
  'detail_douban_rule': instance.detailDoubanRule,
  'detail_imdb_rule': instance.detailImdbRule,
  'detail_poster_rule': instance.detailPosterRule,
  'detail_tags_rule': instance.detailTagsRule,
  'detail_hr_rule': instance.detailHrRule,
  'alive': instance.alive,
  'page_pieces_hash_api': instance.pagePiecesHashApi,
  'pieces_repeat': instance.piecesRepeat,
  'proxy': instance.proxy,
  'structure': instance.structure,
  'type': instance.type,
  'nation': instance.nation,
  'my_email_rule': instance.myEmailRule,
  'my_username_rule': instance.myUsernameRule,
  'buy_page': instance.buyPage,
  'buy_action': instance.buyAction,
  'level': instance.level.map((k, e) => MapEntry(k, e.toJson())),
};

_SiteLevel _$SiteLevelFromJson(Map<String, dynamic> json) => _SiteLevel(
  levelId: (json['level_id'] as num?)?.toInt() ?? 0,
  level: json['level'] as String? ?? '',
  days: (json['days'] as num?)?.toInt() ?? 0,
  uploaded: json['uploaded'] as String? ?? '0',
  downloaded: json['downloaded'] as String? ?? '0',
  bonus: (json['bonus'] as num?)?.toDouble() ?? 0.0,
  score: (json['score'] as num?)?.toInt() ?? 0,
  ratio: (json['ratio'] as num?)?.toDouble() ?? 0.0,
  torrents: (json['torrents'] as num?)?.toInt() ?? 0,
  leeches: (json['leeches'] as num?)?.toInt() ?? 0,
  seedingDelta: (json['seeding_delta'] as num?)?.toDouble() ?? 0.0,
  keepAccount: json['keep_account'] as bool? ?? false,
  graduation: json['graduation'] as bool? ?? false,
  rights: json['rights'] as String? ?? '',
);

Map<String, dynamic> _$SiteLevelToJson(_SiteLevel instance) =>
    <String, dynamic>{
      'level_id': instance.levelId,
      'level': instance.level,
      'days': instance.days,
      'uploaded': instance.uploaded,
      'downloaded': instance.downloaded,
      'bonus': instance.bonus,
      'score': instance.score,
      'ratio': instance.ratio,
      'torrents': instance.torrents,
      'leeches': instance.leeches,
      'seeding_delta': instance.seedingDelta,
      'keep_account': instance.keepAccount,
      'graduation': instance.graduation,
      'rights': instance.rights,
    };
