// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'option_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_OptionValue _$OptionValueFromJson(Map<String, dynamic> json) => _OptionValue(
  token: json['token'] as String?,
  refreshToken: _dynamicToString(json['refresh_token']),
  server: json['server'] as String?,
  key: json['key'] as String?,
  password: json['password'] as String?,
  apiKey: json['api_key'] as String?,
  secretKey: json['secret_key'] as String?,
  appId: json['app_id'] as String?,
  uids: json['uids'] as String?,
  pushKey: json['pushkey'] as String?,
  deviceKey: json['device_key'] as String?,
  repeat: json['repeat'] as bool?,
  welfare: json['welfare'] as bool?,
  proxy: json['proxy'] as String?,
  telegramToken: json['telegram_token'] as String?,
  telegramChatId: json['telegram_chat_id'] as String?,
  template: json['template'] as String?,
  corpId: json['corp_id'] as String?,
  corpSecret: json['corpsecret'] as String?,
  agentId: json['agent_id'] as String?,
  toUid: json['to_uid'] as String?,
  username: json['username'] as String?,
  cookie: json['cookie'] as String?,
  userAgent: json['user_agent'] as String?,
  todaySay: _dynamicToString(json['todaysay']),
  aliyundriveNotice: json['aliyundrive_notice'] as bool?,
  siteData: json['site_data'] as bool?,
  siteDataSuccess: json['site_data_success'] as bool?,
  todayData: json['today_data'] as bool?,
  packageTorrent: json['package_torrent'] as bool?,
  deleteTorrent: json['delete_torrent'] as bool?,
  rssTorrent: json['rss_torrent'] as bool?,
  pushTorrent: json['push_torrent'] as bool?,
  programUpgrade: json['program_upgrade'] as bool?,
  ptppImport: json['ptpp_import'] as bool?,
  announcement: json['announcement'] as bool?,
  message: json['message'] as bool?,
  signInSuccess: json['sign_in_success'] as bool?,
  cookieSync: json['cookie_sync'] as bool?,
  level: json['level'] as bool?,
  bonus: json['bonus'] as bool?,
  perBonus: json['per_bonus'] as bool?,
  score: json['score'] as bool?,
  ratio: json['ratio'] as bool?,
  seedingVol: json['seeding_vol'] as bool?,
  uploaded: json['uploaded'] as bool?,
  downloaded: json['downloaded'] as bool?,
  seeding: json['seeding'] as bool?,
  leeching: json['leeching'] as bool?,
  invite: json['invite'] as bool?,
  hr: json['hr'] as bool?,
  count: (json['count'] as num?)?.toInt(),
  maxCount: (json['max_count'] as num?)?.toInt(),
  limit: (json['limit'] as num?)?.toInt(),
);

Map<String, dynamic> _$OptionValueToJson(_OptionValue instance) =>
    <String, dynamic>{
      'token': ?instance.token,
      'refresh_token': ?instance.refreshToken,
      'server': ?instance.server,
      'key': ?instance.key,
      'password': ?instance.password,
      'api_key': ?instance.apiKey,
      'secret_key': ?instance.secretKey,
      'app_id': ?instance.appId,
      'uids': ?instance.uids,
      'pushkey': ?instance.pushKey,
      'device_key': ?instance.deviceKey,
      'repeat': ?instance.repeat,
      'welfare': ?instance.welfare,
      'proxy': ?instance.proxy,
      'telegram_token': ?instance.telegramToken,
      'telegram_chat_id': ?instance.telegramChatId,
      'template': ?instance.template,
      'corp_id': ?instance.corpId,
      'corpsecret': ?instance.corpSecret,
      'agent_id': ?instance.agentId,
      'to_uid': ?instance.toUid,
      'username': ?instance.username,
      'cookie': ?instance.cookie,
      'user_agent': ?instance.userAgent,
      'todaysay': ?instance.todaySay,
      'aliyundrive_notice': ?instance.aliyundriveNotice,
      'site_data': ?instance.siteData,
      'site_data_success': ?instance.siteDataSuccess,
      'today_data': ?instance.todayData,
      'package_torrent': ?instance.packageTorrent,
      'delete_torrent': ?instance.deleteTorrent,
      'rss_torrent': ?instance.rssTorrent,
      'push_torrent': ?instance.pushTorrent,
      'program_upgrade': ?instance.programUpgrade,
      'ptpp_import': ?instance.ptppImport,
      'announcement': ?instance.announcement,
      'message': ?instance.message,
      'sign_in_success': ?instance.signInSuccess,
      'cookie_sync': ?instance.cookieSync,
      'level': ?instance.level,
      'bonus': ?instance.bonus,
      'per_bonus': ?instance.perBonus,
      'score': ?instance.score,
      'ratio': ?instance.ratio,
      'seeding_vol': ?instance.seedingVol,
      'uploaded': ?instance.uploaded,
      'downloaded': ?instance.downloaded,
      'seeding': ?instance.seeding,
      'leeching': ?instance.leeching,
      'invite': ?instance.invite,
      'hr': ?instance.hr,
      'count': ?instance.count,
      'max_count': ?instance.maxCount,
      'limit': ?instance.limit,
    };

_Option _$OptionFromJson(Map<String, dynamic> json) => _Option(
  id: (json['id'] as num?)?.toInt(),
  name: json['name'] as String,
  value: OptionValue.fromJson(json['value'] as Map<String, dynamic>),
  isActive: json['is_active'] as bool,
);

Map<String, dynamic> _$OptionToJson(_Option instance) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'value': instance.value,
  'is_active': instance.isActive,
};

_SelectOption _$SelectOptionFromJson(Map<String, dynamic> json) =>
    _SelectOption(name: json['name'] as String, value: json['value'] as String);

Map<String, dynamic> _$SelectOptionToJson(_SelectOption instance) =>
    <String, dynamic>{'name': instance.name, 'value': instance.value};
