// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'option_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_OptionValue _$OptionValueFromJson(Map<String, dynamic> json) => _OptionValue(
  token: json['token'] as String?,
  refreshToken: _dynamicToString(json['refresh_token']),
  server: json['server'] as String?,
  key: json['key'] as String?,
  password: json['password'] as String?,
  apiKey: json['api_key'] as String?,
  secretKey: json['secret_key'] as String?,
  appId: json['app_id'] as String?,
  uids: json['uids'] as String?,
  pushKey: json['pushkey'] as String?,
  deviceKey: json['device_key'] as String?,
  repeat: json['repeat'] as bool?,
  welfare: json['welfare'] as bool?,
  proxy: json['proxy'] as String?,
  telegramToken: json['telegram_token'] as String?,
  telegramChatId: json['telegram_chat_id'] as String?,
  template: json['template'] as String?,
  corpId: json['corp_id'] as String?,
  corpSecret: json['corpsecret'] as String?,
  agentId: json['agent_id'] as String?,
  toUid: json['to_uid'] as String?,
  username: json['username'] as String?,
  cookie: json['cookie'] as String?,
  userAgent: json['user_agent'] as String?,
  todaySay: _dynamicToString(json['todaysay']),
  aliyundriveNotice: json['aliyundrive_notice'] as bool?,
  siteData: json['site_data'] as bool?,
  siteDataSuccess: json['site_data_success'] as bool?,
  todayData: json['today_data'] as bool?,
  packageTorrent: json['package_torrent'] as bool?,
  deleteTorrent: json['delete_torrent'] as bool?,
  rssTorrent: json['rss_torrent'] as bool?,
  pushTorrent: json['push_torrent'] as bool?,
  programUpgrade: json['program_upgrade'] as bool?,
  ptppImport: json['ptpp_import'] as bool?,
  announcement: json['announcement'] as bool?,
  message: json['message'] as bool?,
  signInSuccess: json['sign_in_success'] as bool?,
  cookieSync: json['cookie_sync'] as bool?,
  level: json['level'] as bool?,
  bonus: json['bonus'] as bool?,
  perBonus: json['per_bonus'] as bool?,
  score: json['score'] as bool?,
  ratio: json['ratio'] as bool?,
  seedingVol: json['seeding_vol'] as bool?,
  uploaded: json['uploaded'] as bool?,
  downloaded: json['downloaded'] as bool?,
  seeding: json['seeding'] as bool?,
  leeching: json['leeching'] as bool?,
  invite: json['invite'] as bool?,
  hr: json['hr'] as bool?,
  count: (json['count'] as num?)?.toInt(),
  maxCount: (json['max_count'] as num?)?.toInt(),
  limit: (json['limit'] as num?)?.toInt(),
);

Map<String, dynamic> _$OptionValueToJson(
  _OptionValue instance,
) => <String, dynamic>{
  if (instance.token case final value?) 'token': value,
  if (instance.refreshToken case final value?) 'refresh_token': value,
  if (instance.server case final value?) 'server': value,
  if (instance.key case final value?) 'key': value,
  if (instance.password case final value?) 'password': value,
  if (instance.apiKey case final value?) 'api_key': value,
  if (instance.secretKey case final value?) 'secret_key': value,
  if (instance.appId case final value?) 'app_id': value,
  if (instance.uids case final value?) 'uids': value,
  if (instance.pushKey case final value?) 'pushkey': value,
  if (instance.deviceKey case final value?) 'device_key': value,
  if (instance.repeat case final value?) 'repeat': value,
  if (instance.welfare case final value?) 'welfare': value,
  if (instance.proxy case final value?) 'proxy': value,
  if (instance.telegramToken case final value?) 'telegram_token': value,
  if (instance.telegramChatId case final value?) 'telegram_chat_id': value,
  if (instance.template case final value?) 'template': value,
  if (instance.corpId case final value?) 'corp_id': value,
  if (instance.corpSecret case final value?) 'corpsecret': value,
  if (instance.agentId case final value?) 'agent_id': value,
  if (instance.toUid case final value?) 'to_uid': value,
  if (instance.username case final value?) 'username': value,
  if (instance.cookie case final value?) 'cookie': value,
  if (instance.userAgent case final value?) 'user_agent': value,
  if (instance.todaySay case final value?) 'todaysay': value,
  if (instance.aliyundriveNotice case final value?) 'aliyundrive_notice': value,
  if (instance.siteData case final value?) 'site_data': value,
  if (instance.siteDataSuccess case final value?) 'site_data_success': value,
  if (instance.todayData case final value?) 'today_data': value,
  if (instance.packageTorrent case final value?) 'package_torrent': value,
  if (instance.deleteTorrent case final value?) 'delete_torrent': value,
  if (instance.rssTorrent case final value?) 'rss_torrent': value,
  if (instance.pushTorrent case final value?) 'push_torrent': value,
  if (instance.programUpgrade case final value?) 'program_upgrade': value,
  if (instance.ptppImport case final value?) 'ptpp_import': value,
  if (instance.announcement case final value?) 'announcement': value,
  if (instance.message case final value?) 'message': value,
  if (instance.signInSuccess case final value?) 'sign_in_success': value,
  if (instance.cookieSync case final value?) 'cookie_sync': value,
  if (instance.level case final value?) 'level': value,
  if (instance.bonus case final value?) 'bonus': value,
  if (instance.perBonus case final value?) 'per_bonus': value,
  if (instance.score case final value?) 'score': value,
  if (instance.ratio case final value?) 'ratio': value,
  if (instance.seedingVol case final value?) 'seeding_vol': value,
  if (instance.uploaded case final value?) 'uploaded': value,
  if (instance.downloaded case final value?) 'downloaded': value,
  if (instance.seeding case final value?) 'seeding': value,
  if (instance.leeching case final value?) 'leeching': value,
  if (instance.invite case final value?) 'invite': value,
  if (instance.hr case final value?) 'hr': value,
  if (instance.count case final value?) 'count': value,
  if (instance.maxCount case final value?) 'max_count': value,
  if (instance.limit case final value?) 'limit': value,
};

_Option _$OptionFromJson(Map<String, dynamic> json) => _Option(
  id: (json['id'] as num?)?.toInt(),
  name: json['name'] as String,
  value: OptionValue.fromJson(json['value'] as Map<String, dynamic>),
  isActive: json['is_active'] as bool,
);

Map<String, dynamic> _$OptionToJson(_Option instance) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'value': instance.value.toJson(),
  'is_active': instance.isActive,
};

_SelectOption _$SelectOptionFromJson(Map<String, dynamic> json) =>
    _SelectOption(name: json['name'] as String, value: json['value'] as String);

Map<String, dynamic> _$SelectOptionToJson(_SelectOption instance) =>
    <String, dynamic>{'name': instance.name, 'value': instance.value};
