// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'qbittorrent_preferences.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_QbittorrentPreferences _$QbittorrentPreferencesFromJson(
  Map<String, dynamic> json,
) => _QbittorrentPreferences(
  addStoppedEnabled: json['add_stopped_enabled'] as bool? ?? false,
  addToTopOfQueue: json['add_to_top_of_queue'] as bool? ?? false,
  addTrackers: json['add_trackers'] as String? ?? '',
  addTrackersEnabled: json['add_trackers_enabled'] as bool? ?? false,
  addTrackersFromUrlEnabled:
      json['add_trackers_from_url_enabled'] as bool? ?? false,
  addTrackersUrl: json['add_trackers_url'] as String? ?? '',
  addTrackersUrlList: json['add_trackers_url_list'] as String? ?? '',
  altDlLimit: (json['alt_dl_limit'] as num?)?.toInt() ?? 0,
  altUpLimit: (json['alt_up_limit'] as num?)?.toInt() ?? 0,
  alternativeWebuiEnabled: json['alternative_webui_enabled'] as bool? ?? false,
  alternativeWebuiPath: json['alternative_webui_path'] as String? ?? '',
  announceIp: json['announce_ip'] as String? ?? '',
  announcePort: (json['announce_port'] as num?)?.toInt() ?? 0,
  announceToAllTiers: json['announce_to_all_tiers'] as bool? ?? true,
  announceToAllTrackers: json['announce_to_all_trackers'] as bool? ?? true,
  anonymousMode: json['anonymous_mode'] as bool? ?? false,
  appInstanceName: json['app_instance_name'] as String? ?? '',
  asyncIoThreads: (json['async_io_threads'] as num?)?.toInt() ?? 10,
  autoDeleteMode: (json['auto_delete_mode'] as num?)?.toInt() ?? 0,
  autoTmmEnabled: json['auto_tmm_enabled'] as bool? ?? false,
  autorunEnabled: json['autorun_enabled'] as bool? ?? false,
  autorunOnTorrentAddedEnabled:
      json['autorun_on_torrent_added_enabled'] as bool? ?? false,
  autorunOnTorrentAddedProgram:
      json['autorun_on_torrent_added_program'] as String? ?? '',
  autorunProgram: json['autorun_program'] as String? ?? '',
  bannedIPs: json['banned_IPs'] as String? ?? '',
  bdecodeDepthLimit: (json['bdecode_depth_limit'] as num?)?.toInt() ?? 100,
  bdecodeTokenLimit: (json['bdecode_token_limit'] as num?)?.toInt() ?? 10000000,
  bittorrentProtocol: (json['bittorrent_protocol'] as num?)?.toInt() ?? 0,
  blockPeersOnPrivilegedPorts:
      json['block_peers_on_privileged_ports'] as bool? ?? false,
  bypassAuthSubnetWhitelist:
      json['bypass_auth_subnet_whitelist'] as String? ?? '',
  bypassAuthSubnetWhitelistEnabled:
      json['bypass_auth_subnet_whitelist_enabled'] as bool? ?? false,
  bypassLocalAuth: json['bypass_local_auth'] as bool? ?? false,
  categoryChangedTmmEnabled:
      json['category_changed_tmm_enabled'] as bool? ?? true,
  checkingMemoryUse: (json['checking_memory_use'] as num?)?.toInt() ?? 32,
  confirmTorrentDeletion: json['confirm_torrent_deletion'] as bool? ?? true,
  confirmTorrentRecheck: json['confirm_torrent_recheck'] as bool? ?? true,
  connectionSpeed: (json['connection_speed'] as num?)?.toInt() ?? 30,
  currentInterfaceAddress: json['current_interface_address'] as String? ?? '',
  currentInterfaceName: json['current_interface_name'] as String? ?? '',
  currentNetworkInterface: json['current_network_interface'] as String? ?? '',
  deleteTorrentContentFiles:
      json['delete_torrent_content_files'] as bool? ?? false,
  dht: json['dht'] as bool? ?? false,
  dhtBootstrapNodes: json['dht_bootstrap_nodes'] as String? ?? '',
  diskCache: (json['disk_cache'] as num?)?.toInt() ?? -1,
  diskCacheTtl: (json['disk_cache_ttl'] as num?)?.toInt() ?? 60,
  diskIoReadMode: (json['disk_io_read_mode'] as num?)?.toInt() ?? 0,
  diskIoType: (json['disk_io_type'] as num?)?.toInt() ?? 0,
  diskIoWriteMode: (json['disk_io_write_mode'] as num?)?.toInt() ?? 0,
  diskQueueSize: (json['disk_queue_size'] as num?)?.toInt() ?? 0,
  dlLimit: (json['dl_limit'] as num?)?.toInt() ?? 0,
  dontCountSlowTorrents: json['dont_count_slow_torrents'] as bool? ?? false,
  dyndnsDomain: json['dyndns_domain'] as String? ?? '',
  dyndnsEnabled: json['dyndns_enabled'] as bool? ?? false,
  dyndnsPassword: json['dyndns_password'] as String? ?? '',
  dyndnsService: (json['dyndns_service'] as num?)?.toInt() ?? 0,
  dyndnsUsername: json['dyndns_username'] as String? ?? '',
  embeddedTrackerPort: (json['embedded_tracker_port'] as num?)?.toInt() ?? 0,
  embeddedTrackerPortForwarding:
      json['embedded_tracker_port_forwarding'] as bool? ?? false,
  enableCoalesceReadWrite: json['enable_coalesce_read_write'] as bool? ?? false,
  enableEmbeddedTracker: json['enable_embedded_tracker'] as bool? ?? false,
  enableMultiConnectionsFromSameIp:
      json['enable_multi_connections_from_same_ip'] as bool? ?? true,
  enablePieceExtentAffinity:
      json['enable_piece_extent_affinity'] as bool? ?? false,
  enableUploadSuggestions: json['enable_upload_suggestions'] as bool? ?? false,
  encryption: (json['encryption'] as num?)?.toInt() ?? 0,
  excludedFileNames: json['excluded_file_names'] as String? ?? '',
  excludedFileNamesEnabled:
      json['excluded_file_names_enabled'] as bool? ?? false,
  exportDir: json['export_dir'] as String? ?? '',
  exportDirFin: json['export_dir_fin'] as String? ?? '',
  fileLogAge: (json['file_log_age'] as num?)?.toInt() ?? 1,
  fileLogAgeType: (json['file_log_age_type'] as num?)?.toInt() ?? 1,
  fileLogBackupEnabled: json['file_log_backup_enabled'] as bool? ?? true,
  fileLogDeleteOld: json['file_log_delete_old'] as bool? ?? true,
  fileLogEnabled: json['file_log_enabled'] as bool? ?? true,
  fileLogMaxSize: (json['file_log_max_size'] as num?)?.toInt() ?? 65,
  fileLogPath: json['file_log_path'] as String? ?? '',
  filePoolSize: (json['file_pool_size'] as num?)?.toInt() ?? 100,
  hashingThreads: (json['hashing_threads'] as num?)?.toInt() ?? 1,
  i2pAddress: json['i2p_address'] as String? ?? '127.0.0.1',
  i2pEnabled: json['i2p_enabled'] as bool? ?? false,
  i2pInboundLength: (json['i2p_inbound_length'] as num?)?.toInt() ?? 3,
  i2pInboundQuantity: (json['i2p_inbound_quantity'] as num?)?.toInt() ?? 3,
  i2pMixedMode: json['i2p_mixed_mode'] as bool? ?? false,
  i2pOutboundLength: (json['i2p_outbound_length'] as num?)?.toInt() ?? 3,
  i2pOutboundQuantity: (json['i2p_outbound_quantity'] as num?)?.toInt() ?? 3,
  i2pPort: (json['i2p_port'] as num?)?.toInt() ?? 7656,
  idnSupportEnabled: json['idn_support_enabled'] as bool? ?? true,
  ignoreSslErrors: json['ignore_ssl_errors'] as bool? ?? false,
  incompleteFilesExt: json['incomplete_files_ext'] as bool? ?? false,
  ipFilterEnabled: json['ip_filter_enabled'] as bool? ?? false,
  ipFilterPath: json['ip_filter_path'] as String? ?? '',
  ipFilterTrackers: json['ip_filter_trackers'] as bool? ?? false,
  limitLanPeers: json['limit_lan_peers'] as bool? ?? true,
  limitTcpOverhead: json['limit_tcp_overhead'] as bool? ?? false,
  limitUtpRate: json['limit_utp_rate'] as bool? ?? true,
  listenPort: (json['listen_port'] as num?)?.toInt() ?? 0,
  locale: json['locale'] as String? ?? '',
  lsd: json['lsd'] as bool? ?? true,
  mailNotificationAuthEnabled:
      json['mail_notification_auth_enabled'] as bool? ?? false,
  mailNotificationEmail: json['mail_notification_email'] as String? ?? '',
  mailNotificationEnabled: json['mail_notification_enabled'] as bool? ?? false,
  mailNotificationPassword: json['mail_notification_password'] as String? ?? '',
  mailNotificationSender: json['mail_notification_sender'] as String? ?? '',
  mailNotificationSmtp: json['mail_notification_smtp'] as String? ?? '',
  mailNotificationSslEnabled:
      json['mail_notification_ssl_enabled'] as bool? ?? false,
  mailNotificationUsername: json['mail_notification_username'] as String? ?? '',
  markOfTheWeb: json['mark_of_the_web'] as bool? ?? true,
  maxActiveCheckingTorrents:
      (json['max_active_checking_torrents'] as num?)?.toInt() ?? 1,
  maxActiveDownloads: (json['max_active_downloads'] as num?)?.toInt() ?? 3,
  maxActiveTorrents: (json['max_active_torrents'] as num?)?.toInt() ?? 5,
  maxActiveUploads: (json['max_active_uploads'] as num?)?.toInt() ?? 3,
  maxConcurrentHttpAnnounces:
      (json['max_concurrent_http_announces'] as num?)?.toInt() ?? 50,
  maxConnec: (json['max_connec'] as num?)?.toInt() ?? 500,
  maxConnecPerTorrent: (json['max_connec_per_torrent'] as num?)?.toInt() ?? 100,
  maxInactiveSeedingTime:
      (json['max_inactive_seeding_time'] as num?)?.toInt() ?? -1,
  maxInactiveSeedingTimeEnabled:
      json['max_inactive_seeding_time_enabled'] as bool? ?? false,
  maxRatio: json['max_ratio'] as num? ?? -1,
  maxRatioAct: (json['max_ratio_act'] as num?)?.toInt() ?? 0,
  maxRatioEnabled: json['max_ratio_enabled'] as bool? ?? false,
  maxSeedingTime: (json['max_seeding_time'] as num?)?.toInt() ?? -1,
  maxSeedingTimeEnabled: json['max_seeding_time_enabled'] as bool? ?? false,
  maxUploads: (json['max_uploads'] as num?)?.toInt() ?? 20,
  maxUploadsPerTorrent:
      (json['max_uploads_per_torrent'] as num?)?.toInt() ?? 10,
  memoryWorkingSetLimit:
      (json['memory_working_set_limit'] as num?)?.toInt() ?? 4096,
  mergeTrackers: json['merge_trackers'] as bool? ?? false,
  outgoingPortsMax: (json['outgoing_ports_max'] as num?)?.toInt() ?? 0,
  outgoingPortsMin: (json['outgoing_ports_min'] as num?)?.toInt() ?? 0,
  peerTos: (json['peer_tos'] as num?)?.toInt() ?? 4,
  peerTurnover: (json['peer_turnover'] as num?)?.toInt() ?? 4,
  peerTurnoverCutoff: (json['peer_turnover_cutoff'] as num?)?.toInt() ?? 90,
  peerTurnoverInterval:
      (json['peer_turnover_interval'] as num?)?.toInt() ?? 300,
  performanceWarning: json['performance_warning'] as bool? ?? false,
  pex: json['pex'] as bool? ?? true,
  preallocateAll: json['preallocate_all'] as bool? ?? false,
  proxyAuthEnabled: json['proxy_auth_enabled'] as bool? ?? false,
  proxyBittorrent: json['proxy_bittorrent'] as bool? ?? true,
  proxyHostnameLookup: json['proxy_hostname_lookup'] as bool? ?? false,
  proxyIp: json['proxy_ip'] as String? ?? '',
  proxyMisc: json['proxy_misc'] as bool? ?? true,
  proxyPassword: json['proxy_password'] as String? ?? '',
  proxyPeerConnections: json['proxy_peer_connections'] as bool? ?? false,
  proxyPort: (json['proxy_port'] as num?)?.toInt() ?? 8080,
  proxyRss: json['proxy_rss'] as bool? ?? true,
  proxyType: json['proxy_type'] as String? ?? 'None',
  proxyUsername: json['proxy_username'] as String? ?? '',
  pythonExecutablePath: json['python_executable_path'] as String? ?? '',
  queueingEnabled: json['queueing_enabled'] as bool? ?? false,
  randomPort: json['random_port'] as bool? ?? false,
  reannounceWhenAddressChanged:
      json['reannounce_when_address_changed'] as bool? ?? false,
  recheckCompletedTorrents:
      json['recheck_completed_torrents'] as bool? ?? false,
  refreshInterval: (json['refresh_interval'] as num?)?.toInt() ?? 1500,
  requestQueueSize: (json['request_queue_size'] as num?)?.toInt() ?? 500,
  resolvePeerCountries: json['resolve_peer_countries'] as bool? ?? true,
  resumeDataStorageType:
      json['resume_data_storage_type'] as String? ?? 'Legacy',
  rssAutoDownloadingEnabled:
      json['rss_auto_downloading_enabled'] as bool? ?? false,
  rssDownloadRepackProperEpisodes:
      json['rss_download_repack_proper_episodes'] as bool? ?? true,
  rssFetchDelay: (json['rss_fetch_delay'] as num?)?.toInt() ?? 2,
  rssMaxArticlesPerFeed:
      (json['rss_max_articles_per_feed'] as num?)?.toInt() ?? 50,
  rssProcessingEnabled: json['rss_processing_enabled'] as bool? ?? false,
  rssRefreshInterval: (json['rss_refresh_interval'] as num?)?.toInt() ?? 30,
  rssSmartEpisodeFilters: json['rss_smart_episode_filters'] as String? ?? '',
  savePath: json['save_path'] as String? ?? '',
  savePathChangedTmmEnabled:
      json['save_path_changed_tmm_enabled'] as bool? ?? true,
  saveResumeDataInterval:
      (json['save_resume_data_interval'] as num?)?.toInt() ?? 60,
  saveStatisticsInterval:
      (json['save_statistics_interval'] as num?)?.toInt() ?? 15,
  scanDirs: json['scan_dirs'] as Map<String, dynamic>? ?? const {},
  scheduleFromHour: (json['schedule_from_hour'] as num?)?.toInt() ?? 8,
  scheduleFromMin: (json['schedule_from_min'] as num?)?.toInt() ?? 0,
  scheduleToHour: (json['schedule_to_hour'] as num?)?.toInt() ?? 20,
  scheduleToMin: (json['schedule_to_min'] as num?)?.toInt() ?? 0,
  schedulerDays: (json['scheduler_days'] as num?)?.toInt() ?? 0,
  schedulerEnabled: json['scheduler_enabled'] as bool? ?? false,
  sendBufferLowWatermark:
      (json['send_buffer_low_watermark'] as num?)?.toInt() ?? 10,
  sendBufferWatermark: (json['send_buffer_watermark'] as num?)?.toInt() ?? 500,
  sendBufferWatermarkFactor:
      (json['send_buffer_watermark_factor'] as num?)?.toInt() ?? 50,
  slowTorrentDlRateThreshold:
      (json['slow_torrent_dl_rate_threshold'] as num?)?.toInt() ?? 2,
  slowTorrentInactiveTimer:
      (json['slow_torrent_inactive_timer'] as num?)?.toInt() ?? 60,
  slowTorrentUlRateThreshold:
      (json['slow_torrent_ul_rate_threshold'] as num?)?.toInt() ?? 2,
  socketBacklogSize: (json['socket_backlog_size'] as num?)?.toInt() ?? 30,
  socketReceiveBufferSize:
      (json['socket_receive_buffer_size'] as num?)?.toInt() ?? 0,
  socketSendBufferSize: (json['socket_send_buffer_size'] as num?)?.toInt() ?? 0,
  sslEnabled: json['ssl_enabled'] as bool? ?? false,
  sslListenPort: (json['ssl_listen_port'] as num?)?.toInt() ?? 0,
  ssrfMitigation: json['ssrf_mitigation'] as bool? ?? true,
  statusBarExternalIp: json['status_bar_external_ip'] as bool? ?? false,
  stopTrackerTimeout: (json['stop_tracker_timeout'] as num?)?.toInt() ?? 2,
  tempPath: json['temp_path'] as String? ?? '',
  tempPathEnabled: json['temp_path_enabled'] as bool? ?? false,
  torrentChangedTmmEnabled:
      json['torrent_changed_tmm_enabled'] as bool? ?? true,
  torrentContentLayout: json['torrent_content_layout'] as String? ?? 'Original',
  torrentContentRemoveOption:
      json['torrent_content_remove_option'] as String? ?? 'Delete',
  torrentFileSizeLimit: (json['torrent_file_size_limit'] as num?)?.toInt() ?? 0,
  torrentStopCondition: json['torrent_stop_condition'] as String? ?? 'None',
  upLimit: (json['up_limit'] as num?)?.toInt() ?? 0,
  uploadChokingAlgorithm:
      (json['upload_choking_algorithm'] as num?)?.toInt() ?? 0,
  uploadSlotsBehavior: (json['upload_slots_behavior'] as num?)?.toInt() ?? 0,
  upnp: json['upnp'] as bool? ?? true,
  upnpLeaseDuration: (json['upnp_lease_duration'] as num?)?.toInt() ?? 0,
  useCategoryPathsInManualMode:
      json['use_category_paths_in_manual_mode'] as bool? ?? false,
  useHttps: json['use_https'] as bool? ?? false,
  useSubcategories: json['use_subcategories'] as bool? ?? false,
  useUnwantedFolder: json['use_unwanted_folder'] as bool? ?? false,
  utpTcpMixedMode: (json['utp_tcp_mixed_mode'] as num?)?.toInt() ?? 0,
  validateHttpsTrackerCertificate:
      json['validate_https_tracker_certificate'] as bool? ?? true,
  webUiAddress: json['web_ui_address'] as String? ?? '*',
  webUiBanDuration: (json['web_ui_ban_duration'] as num?)?.toInt() ?? 3600,
  webUiClickjackingProtectionEnabled:
      json['web_ui_clickjacking_protection_enabled'] as bool? ?? false,
  webUiCsrfProtectionEnabled:
      json['web_ui_csrf_protection_enabled'] as bool? ?? false,
  webUiCustomHttpHeaders: json['web_ui_custom_http_headers'] as String? ?? '',
  webUiDomainList: json['web_ui_domain_list'] as String? ?? '*',
  webUiHostHeaderValidationEnabled:
      json['web_ui_host_header_validation_enabled'] as bool? ?? false,
  webUiHttpsCertPath: json['web_ui_https_cert_path'] as String? ?? '',
  webUiHttpsKeyPath: json['web_ui_https_key_path'] as String? ?? '',
  webUiMaxAuthFailCount:
      (json['web_ui_max_auth_fail_count'] as num?)?.toInt() ?? 5,
  webUiPort: (json['web_ui_port'] as num?)?.toInt() ?? 0,
  webUiReverseProxiesList: json['web_ui_reverse_proxies_list'] as String? ?? '',
  webUiReverseProxyEnabled:
      json['web_ui_reverse_proxy_enabled'] as bool? ?? false,
  webUiSecureCookieEnabled:
      json['web_ui_secure_cookie_enabled'] as bool? ?? false,
  webUiSessionTimeout:
      (json['web_ui_session_timeout'] as num?)?.toInt() ?? 3600,
  webUiUpnp: json['web_ui_upnp'] as bool? ?? false,
  webUiUseCustomHttpHeadersEnabled:
      json['web_ui_use_custom_http_headers_enabled'] as bool? ?? false,
  webUiUsername: json['web_ui_username'] as String? ?? '',
);

Map<String, dynamic> _$QbittorrentPreferencesToJson(
  _QbittorrentPreferences instance,
) => <String, dynamic>{
  'add_stopped_enabled': instance.addStoppedEnabled,
  'add_to_top_of_queue': instance.addToTopOfQueue,
  'add_trackers': instance.addTrackers,
  'add_trackers_enabled': instance.addTrackersEnabled,
  'add_trackers_from_url_enabled': instance.addTrackersFromUrlEnabled,
  'add_trackers_url': instance.addTrackersUrl,
  'add_trackers_url_list': instance.addTrackersUrlList,
  'alt_dl_limit': instance.altDlLimit,
  'alt_up_limit': instance.altUpLimit,
  'alternative_webui_enabled': instance.alternativeWebuiEnabled,
  'alternative_webui_path': instance.alternativeWebuiPath,
  'announce_ip': instance.announceIp,
  'announce_port': instance.announcePort,
  'announce_to_all_tiers': instance.announceToAllTiers,
  'announce_to_all_trackers': instance.announceToAllTrackers,
  'anonymous_mode': instance.anonymousMode,
  'app_instance_name': instance.appInstanceName,
  'async_io_threads': instance.asyncIoThreads,
  'auto_delete_mode': instance.autoDeleteMode,
  'auto_tmm_enabled': instance.autoTmmEnabled,
  'autorun_enabled': instance.autorunEnabled,
  'autorun_on_torrent_added_enabled': instance.autorunOnTorrentAddedEnabled,
  'autorun_on_torrent_added_program': instance.autorunOnTorrentAddedProgram,
  'autorun_program': instance.autorunProgram,
  'banned_IPs': instance.bannedIPs,
  'bdecode_depth_limit': instance.bdecodeDepthLimit,
  'bdecode_token_limit': instance.bdecodeTokenLimit,
  'bittorrent_protocol': instance.bittorrentProtocol,
  'block_peers_on_privileged_ports': instance.blockPeersOnPrivilegedPorts,
  'bypass_auth_subnet_whitelist': instance.bypassAuthSubnetWhitelist,
  'bypass_auth_subnet_whitelist_enabled':
      instance.bypassAuthSubnetWhitelistEnabled,
  'bypass_local_auth': instance.bypassLocalAuth,
  'category_changed_tmm_enabled': instance.categoryChangedTmmEnabled,
  'checking_memory_use': instance.checkingMemoryUse,
  'confirm_torrent_deletion': instance.confirmTorrentDeletion,
  'confirm_torrent_recheck': instance.confirmTorrentRecheck,
  'connection_speed': instance.connectionSpeed,
  'current_interface_address': instance.currentInterfaceAddress,
  'current_interface_name': instance.currentInterfaceName,
  'current_network_interface': instance.currentNetworkInterface,
  'delete_torrent_content_files': instance.deleteTorrentContentFiles,
  'dht': instance.dht,
  'dht_bootstrap_nodes': instance.dhtBootstrapNodes,
  'disk_cache': instance.diskCache,
  'disk_cache_ttl': instance.diskCacheTtl,
  'disk_io_read_mode': instance.diskIoReadMode,
  'disk_io_type': instance.diskIoType,
  'disk_io_write_mode': instance.diskIoWriteMode,
  'disk_queue_size': instance.diskQueueSize,
  'dl_limit': instance.dlLimit,
  'dont_count_slow_torrents': instance.dontCountSlowTorrents,
  'dyndns_domain': instance.dyndnsDomain,
  'dyndns_enabled': instance.dyndnsEnabled,
  'dyndns_password': instance.dyndnsPassword,
  'dyndns_service': instance.dyndnsService,
  'dyndns_username': instance.dyndnsUsername,
  'embedded_tracker_port': instance.embeddedTrackerPort,
  'embedded_tracker_port_forwarding': instance.embeddedTrackerPortForwarding,
  'enable_coalesce_read_write': instance.enableCoalesceReadWrite,
  'enable_embedded_tracker': instance.enableEmbeddedTracker,
  'enable_multi_connections_from_same_ip':
      instance.enableMultiConnectionsFromSameIp,
  'enable_piece_extent_affinity': instance.enablePieceExtentAffinity,
  'enable_upload_suggestions': instance.enableUploadSuggestions,
  'encryption': instance.encryption,
  'excluded_file_names': instance.excludedFileNames,
  'excluded_file_names_enabled': instance.excludedFileNamesEnabled,
  'export_dir': instance.exportDir,
  'export_dir_fin': instance.exportDirFin,
  'file_log_age': instance.fileLogAge,
  'file_log_age_type': instance.fileLogAgeType,
  'file_log_backup_enabled': instance.fileLogBackupEnabled,
  'file_log_delete_old': instance.fileLogDeleteOld,
  'file_log_enabled': instance.fileLogEnabled,
  'file_log_max_size': instance.fileLogMaxSize,
  'file_log_path': instance.fileLogPath,
  'file_pool_size': instance.filePoolSize,
  'hashing_threads': instance.hashingThreads,
  'i2p_address': instance.i2pAddress,
  'i2p_enabled': instance.i2pEnabled,
  'i2p_inbound_length': instance.i2pInboundLength,
  'i2p_inbound_quantity': instance.i2pInboundQuantity,
  'i2p_mixed_mode': instance.i2pMixedMode,
  'i2p_outbound_length': instance.i2pOutboundLength,
  'i2p_outbound_quantity': instance.i2pOutboundQuantity,
  'i2p_port': instance.i2pPort,
  'idn_support_enabled': instance.idnSupportEnabled,
  'ignore_ssl_errors': instance.ignoreSslErrors,
  'incomplete_files_ext': instance.incompleteFilesExt,
  'ip_filter_enabled': instance.ipFilterEnabled,
  'ip_filter_path': instance.ipFilterPath,
  'ip_filter_trackers': instance.ipFilterTrackers,
  'limit_lan_peers': instance.limitLanPeers,
  'limit_tcp_overhead': instance.limitTcpOverhead,
  'limit_utp_rate': instance.limitUtpRate,
  'listen_port': instance.listenPort,
  'locale': instance.locale,
  'lsd': instance.lsd,
  'mail_notification_auth_enabled': instance.mailNotificationAuthEnabled,
  'mail_notification_email': instance.mailNotificationEmail,
  'mail_notification_enabled': instance.mailNotificationEnabled,
  'mail_notification_password': instance.mailNotificationPassword,
  'mail_notification_sender': instance.mailNotificationSender,
  'mail_notification_smtp': instance.mailNotificationSmtp,
  'mail_notification_ssl_enabled': instance.mailNotificationSslEnabled,
  'mail_notification_username': instance.mailNotificationUsername,
  'mark_of_the_web': instance.markOfTheWeb,
  'max_active_checking_torrents': instance.maxActiveCheckingTorrents,
  'max_active_downloads': instance.maxActiveDownloads,
  'max_active_torrents': instance.maxActiveTorrents,
  'max_active_uploads': instance.maxActiveUploads,
  'max_concurrent_http_announces': instance.maxConcurrentHttpAnnounces,
  'max_connec': instance.maxConnec,
  'max_connec_per_torrent': instance.maxConnecPerTorrent,
  'max_inactive_seeding_time': instance.maxInactiveSeedingTime,
  'max_inactive_seeding_time_enabled': instance.maxInactiveSeedingTimeEnabled,
  'max_ratio': instance.maxRatio,
  'max_ratio_act': instance.maxRatioAct,
  'max_ratio_enabled': instance.maxRatioEnabled,
  'max_seeding_time': instance.maxSeedingTime,
  'max_seeding_time_enabled': instance.maxSeedingTimeEnabled,
  'max_uploads': instance.maxUploads,
  'max_uploads_per_torrent': instance.maxUploadsPerTorrent,
  'memory_working_set_limit': instance.memoryWorkingSetLimit,
  'merge_trackers': instance.mergeTrackers,
  'outgoing_ports_max': instance.outgoingPortsMax,
  'outgoing_ports_min': instance.outgoingPortsMin,
  'peer_tos': instance.peerTos,
  'peer_turnover': instance.peerTurnover,
  'peer_turnover_cutoff': instance.peerTurnoverCutoff,
  'peer_turnover_interval': instance.peerTurnoverInterval,
  'performance_warning': instance.performanceWarning,
  'pex': instance.pex,
  'preallocate_all': instance.preallocateAll,
  'proxy_auth_enabled': instance.proxyAuthEnabled,
  'proxy_bittorrent': instance.proxyBittorrent,
  'proxy_hostname_lookup': instance.proxyHostnameLookup,
  'proxy_ip': instance.proxyIp,
  'proxy_misc': instance.proxyMisc,
  'proxy_password': instance.proxyPassword,
  'proxy_peer_connections': instance.proxyPeerConnections,
  'proxy_port': instance.proxyPort,
  'proxy_rss': instance.proxyRss,
  'proxy_type': instance.proxyType,
  'proxy_username': instance.proxyUsername,
  'python_executable_path': instance.pythonExecutablePath,
  'queueing_enabled': instance.queueingEnabled,
  'random_port': instance.randomPort,
  'reannounce_when_address_changed': instance.reannounceWhenAddressChanged,
  'recheck_completed_torrents': instance.recheckCompletedTorrents,
  'refresh_interval': instance.refreshInterval,
  'request_queue_size': instance.requestQueueSize,
  'resolve_peer_countries': instance.resolvePeerCountries,
  'resume_data_storage_type': instance.resumeDataStorageType,
  'rss_auto_downloading_enabled': instance.rssAutoDownloadingEnabled,
  'rss_download_repack_proper_episodes':
      instance.rssDownloadRepackProperEpisodes,
  'rss_fetch_delay': instance.rssFetchDelay,
  'rss_max_articles_per_feed': instance.rssMaxArticlesPerFeed,
  'rss_processing_enabled': instance.rssProcessingEnabled,
  'rss_refresh_interval': instance.rssRefreshInterval,
  'rss_smart_episode_filters': instance.rssSmartEpisodeFilters,
  'save_path': instance.savePath,
  'save_path_changed_tmm_enabled': instance.savePathChangedTmmEnabled,
  'save_resume_data_interval': instance.saveResumeDataInterval,
  'save_statistics_interval': instance.saveStatisticsInterval,
  'scan_dirs': instance.scanDirs,
  'schedule_from_hour': instance.scheduleFromHour,
  'schedule_from_min': instance.scheduleFromMin,
  'schedule_to_hour': instance.scheduleToHour,
  'schedule_to_min': instance.scheduleToMin,
  'scheduler_days': instance.schedulerDays,
  'scheduler_enabled': instance.schedulerEnabled,
  'send_buffer_low_watermark': instance.sendBufferLowWatermark,
  'send_buffer_watermark': instance.sendBufferWatermark,
  'send_buffer_watermark_factor': instance.sendBufferWatermarkFactor,
  'slow_torrent_dl_rate_threshold': instance.slowTorrentDlRateThreshold,
  'slow_torrent_inactive_timer': instance.slowTorrentInactiveTimer,
  'slow_torrent_ul_rate_threshold': instance.slowTorrentUlRateThreshold,
  'socket_backlog_size': instance.socketBacklogSize,
  'socket_receive_buffer_size': instance.socketReceiveBufferSize,
  'socket_send_buffer_size': instance.socketSendBufferSize,
  'ssl_enabled': instance.sslEnabled,
  'ssl_listen_port': instance.sslListenPort,
  'ssrf_mitigation': instance.ssrfMitigation,
  'status_bar_external_ip': instance.statusBarExternalIp,
  'stop_tracker_timeout': instance.stopTrackerTimeout,
  'temp_path': instance.tempPath,
  'temp_path_enabled': instance.tempPathEnabled,
  'torrent_changed_tmm_enabled': instance.torrentChangedTmmEnabled,
  'torrent_content_layout': instance.torrentContentLayout,
  'torrent_content_remove_option': instance.torrentContentRemoveOption,
  'torrent_file_size_limit': instance.torrentFileSizeLimit,
  'torrent_stop_condition': instance.torrentStopCondition,
  'up_limit': instance.upLimit,
  'upload_choking_algorithm': instance.uploadChokingAlgorithm,
  'upload_slots_behavior': instance.uploadSlotsBehavior,
  'upnp': instance.upnp,
  'upnp_lease_duration': instance.upnpLeaseDuration,
  'use_category_paths_in_manual_mode': instance.useCategoryPathsInManualMode,
  'use_https': instance.useHttps,
  'use_subcategories': instance.useSubcategories,
  'use_unwanted_folder': instance.useUnwantedFolder,
  'utp_tcp_mixed_mode': instance.utpTcpMixedMode,
  'validate_https_tracker_certificate':
      instance.validateHttpsTrackerCertificate,
  'web_ui_address': instance.webUiAddress,
  'web_ui_ban_duration': instance.webUiBanDuration,
  'web_ui_clickjacking_protection_enabled':
      instance.webUiClickjackingProtectionEnabled,
  'web_ui_csrf_protection_enabled': instance.webUiCsrfProtectionEnabled,
  'web_ui_custom_http_headers': instance.webUiCustomHttpHeaders,
  'web_ui_domain_list': instance.webUiDomainList,
  'web_ui_host_header_validation_enabled':
      instance.webUiHostHeaderValidationEnabled,
  'web_ui_https_cert_path': instance.webUiHttpsCertPath,
  'web_ui_https_key_path': instance.webUiHttpsKeyPath,
  'web_ui_max_auth_fail_count': instance.webUiMaxAuthFailCount,
  'web_ui_port': instance.webUiPort,
  'web_ui_reverse_proxies_list': instance.webUiReverseProxiesList,
  'web_ui_reverse_proxy_enabled': instance.webUiReverseProxyEnabled,
  'web_ui_secure_cookie_enabled': instance.webUiSecureCookieEnabled,
  'web_ui_session_timeout': instance.webUiSessionTimeout,
  'web_ui_upnp': instance.webUiUpnp,
  'web_ui_use_custom_http_headers_enabled':
      instance.webUiUseCustomHttpHeadersEnabled,
  'web_ui_username': instance.webUiUsername,
};
