// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transmission_preferences.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_TransmissionPreferences _$TransmissionPreferencesFromJson(
  Map<String, dynamic> json,
) => _TransmissionPreferences(
  rpcVersion: (json['rpc-version'] as num?)?.toInt() ?? 0,
  rpcVersionSemver: json['rpc-version-semver'] as String? ?? '',
  rpcVersionMinimum: (json['rpc-version-minimum'] as num?)?.toInt() ?? 0,
  version: json['version'] as String? ?? '',
  altSpeedDown: (json['alt-speed-down'] as num?)?.toInt() ?? 100,
  altSpeedEnabled: json['alt-speed-enabled'] as bool? ?? false,
  altSpeedTimeBegin: (json['alt-speed-time-begin'] as num?)?.toInt() ?? 540,
  altSpeedTimeDay: (json['alt-speed-time-day'] as num?)?.toInt() ?? 127,
  altSpeedTimeEnabled: json['alt-speed-time-enabled'] as bool? ?? false,
  altSpeedTimeEnd: (json['alt-speed-time-end'] as num?)?.toInt() ?? 1020,
  altSpeedUp: (json['alt-speed-up'] as num?)?.toInt() ?? 100,
  antiBruteForceEnabled: json['anti-brute-force-enabled'] as bool? ?? false,
  antiBruteForceThreshold:
      (json['anti-brute-force-threshold'] as num?)?.toInt() ?? 100,
  blocklistEnabled: json['blocklist-enabled'] as bool? ?? false,
  blocklistSize: (json['blocklist-size'] as num?)?.toInt() ?? 0,
  blocklistUrl: json['blocklist-url'] as String? ?? '',
  cacheSizeMb: (json['cache-size-mb'] as num?)?.toInt() ?? 4,
  configDir: json['config-dir'] as String? ?? '',
  defaultTrackers: json['default-trackers'] as String? ?? '',
  dhtEnabled: json['dht-enabled'] as bool? ?? true,
  downloadDir: json['download-dir'] as String? ?? '',
  downloadDirFreeSpace: (json['download-dir-free-space'] as num?)?.toInt() ?? 0,
  downloadQueueEnabled: json['download-queue-enabled'] as bool? ?? true,
  downloadQueueSize: (json['download-queue-size'] as num?)?.toInt() ?? 5,
  encryption: json['encryption'] as String? ?? 'preferred',
  idleSeedingLimit: (json['idle-seeding-limit'] as num?)?.toInt() ?? 30,
  idleSeedingLimitEnabled: json['idle-seeding-limit-enabled'] as bool? ?? false,
  incompleteDir: json['incomplete-dir'] as String? ?? '',
  incompleteDirEnabled: json['incomplete-dir-enabled'] as bool? ?? false,
  lpdEnabled: json['lpd-enabled'] as bool? ?? false,
  peerLimitGlobal: (json['peer-limit-global'] as num?)?.toInt() ?? 200,
  peerLimitPerTorrent: (json['peer-limit-per-torrent'] as num?)?.toInt() ?? 50,
  peerPort: (json['peer-port'] as num?)?.toInt() ?? 51413,
  peerPortRandomOnStart: json['peer-port-random-on-start'] as bool? ?? false,
  pexEnabled: json['pex-enabled'] as bool? ?? true,
  portForwardingEnabled: json['port-forwarding-enabled'] as bool? ?? true,
  queueStalledEnabled: json['queue-stalled-enabled'] as bool? ?? true,
  queueStalledMinutes: (json['queue-stalled-minutes'] as num?)?.toInt() ?? 30,
  renamePartialFiles: json['rename-partial-files'] as bool? ?? true,
  scriptTorrentAddedEnabled:
      json['script-torrent-added-enabled'] as bool? ?? false,
  scriptTorrentAddedFilename:
      json['script-torrent-added-filename'] as String? ?? '',
  scriptTorrentDoneEnabled:
      json['script-torrent-done-enabled'] as bool? ?? false,
  scriptTorrentDoneFilename:
      json['script-torrent-done-filename'] as String? ?? '',
  scriptTorrentDoneSeedingEnabled:
      json['script-torrent-done-seeding-enabled'] as bool? ?? false,
  scriptTorrentDoneSeedingFilename:
      json['script-torrent-done-seeding-filename'] as String? ?? '',
  seedQueueEnabled: json['seed-queue-enabled'] as bool? ?? false,
  seedQueueSize: (json['seed-queue-size'] as num?)?.toInt() ?? 10,
  seedRatioLimit: (json['seedRatioLimit'] as num?)?.toDouble() ?? 2.0,
  seedRatioLimited: json['seedRatioLimited'] as bool? ?? false,
  sessionId: json['session-id'] as String? ?? '',
  speedLimitDown: (json['speed-limit-down'] as num?)?.toInt() ?? 100,
  speedLimitDownEnabled: json['speed-limit-down-enabled'] as bool? ?? false,
  speedLimitUp: (json['speed-limit-up'] as num?)?.toInt() ?? 100,
  speedLimitUpEnabled: json['speed-limit-up-enabled'] as bool? ?? false,
  startAddedTorrents: json['start-added-torrents'] as bool? ?? true,
  tcpEnabled: json['tcp-enabled'] as bool? ?? true,
  trashOriginalTorrentFiles:
      json['trash-original-torrent-files'] as bool? ?? false,
  utpEnabled: json['utp-enabled'] as bool? ?? false,
);

Map<String, dynamic> _$TransmissionPreferencesToJson(
  _TransmissionPreferences instance,
) => <String, dynamic>{
  'rpc-version': instance.rpcVersion,
  'rpc-version-semver': instance.rpcVersionSemver,
  'rpc-version-minimum': instance.rpcVersionMinimum,
  'version': instance.version,
  'alt-speed-down': instance.altSpeedDown,
  'alt-speed-enabled': instance.altSpeedEnabled,
  'alt-speed-time-begin': instance.altSpeedTimeBegin,
  'alt-speed-time-day': instance.altSpeedTimeDay,
  'alt-speed-time-enabled': instance.altSpeedTimeEnabled,
  'alt-speed-time-end': instance.altSpeedTimeEnd,
  'alt-speed-up': instance.altSpeedUp,
  'anti-brute-force-enabled': instance.antiBruteForceEnabled,
  'anti-brute-force-threshold': instance.antiBruteForceThreshold,
  'blocklist-enabled': instance.blocklistEnabled,
  'blocklist-size': instance.blocklistSize,
  'blocklist-url': instance.blocklistUrl,
  'cache-size-mb': instance.cacheSizeMb,
  'config-dir': instance.configDir,
  'default-trackers': instance.defaultTrackers,
  'dht-enabled': instance.dhtEnabled,
  'download-dir': instance.downloadDir,
  'download-dir-free-space': instance.downloadDirFreeSpace,
  'download-queue-enabled': instance.downloadQueueEnabled,
  'download-queue-size': instance.downloadQueueSize,
  'encryption': instance.encryption,
  'idle-seeding-limit': instance.idleSeedingLimit,
  'idle-seeding-limit-enabled': instance.idleSeedingLimitEnabled,
  'incomplete-dir': instance.incompleteDir,
  'incomplete-dir-enabled': instance.incompleteDirEnabled,
  'lpd-enabled': instance.lpdEnabled,
  'peer-limit-global': instance.peerLimitGlobal,
  'peer-limit-per-torrent': instance.peerLimitPerTorrent,
  'peer-port': instance.peerPort,
  'peer-port-random-on-start': instance.peerPortRandomOnStart,
  'pex-enabled': instance.pexEnabled,
  'port-forwarding-enabled': instance.portForwardingEnabled,
  'queue-stalled-enabled': instance.queueStalledEnabled,
  'queue-stalled-minutes': instance.queueStalledMinutes,
  'rename-partial-files': instance.renamePartialFiles,
  'script-torrent-added-enabled': instance.scriptTorrentAddedEnabled,
  'script-torrent-added-filename': instance.scriptTorrentAddedFilename,
  'script-torrent-done-enabled': instance.scriptTorrentDoneEnabled,
  'script-torrent-done-filename': instance.scriptTorrentDoneFilename,
  'script-torrent-done-seeding-enabled':
      instance.scriptTorrentDoneSeedingEnabled,
  'script-torrent-done-seeding-filename':
      instance.scriptTorrentDoneSeedingFilename,
  'seed-queue-enabled': instance.seedQueueEnabled,
  'seed-queue-size': instance.seedQueueSize,
  'seedRatioLimit': instance.seedRatioLimit,
  'seedRatioLimited': instance.seedRatioLimited,
  'session-id': instance.sessionId,
  'speed-limit-down': instance.speedLimitDown,
  'speed-limit-down-enabled': instance.speedLimitDownEnabled,
  'speed-limit-up': instance.speedLimitUp,
  'speed-limit-up-enabled': instance.speedLimitUpEnabled,
  'start-added-torrents': instance.startAddedTorrents,
  'tcp-enabled': instance.tcpEnabled,
  'trash-original-torrent-files': instance.trashOriginalTorrentFiles,
  'utp-enabled': instance.utpEnabled,
};
