import 'package:freezed_annotation/freezed_annotation.dart';

part 'transmission_preferences.freezed.dart';
part 'transmission_preferences.g.dart';

@freezed
abstract class TransmissionPreferences with _$TransmissionPreferences {
  const factory TransmissionPreferences({
    @JsonKey(name: 'rpc-version') @Default(0) int rpcVersion,
    @JsonKey(name: 'rpc-version-semver') @Default('') String rpcVersionSemver,
    @JsonKey(name: 'rpc-version-minimum') @Default(0) int rpcVersionMinimum,
    @Default('') String version,
    @JsonKey(name: 'alt-speed-down') @Default(100) int altSpeedDown,
    @JsonKey(name: 'alt-speed-enabled') @Default(false) bool altSpeedEnabled,
    @JsonKey(name: 'alt-speed-time-begin') @Default(540) int altSpeedTimeBegin,
    @JsonKey(name: 'alt-speed-time-day') @Default(127) int altSpeedTimeDay,
    @JsonKey(name: 'alt-speed-time-enabled') @Default(false) bool altSpeedTimeEnabled,
    @JsonKey(name: 'alt-speed-time-end') @Default(1020) int altSpeedTimeEnd,
    @JsonKey(name: 'alt-speed-up') @Default(100) int altSpeedUp,
    @JsonKey(name: 'anti-brute-force-enabled') @Default(false) bool antiBruteForceEnabled,
    @JsonKey(name: 'anti-brute-force-threshold') @Default(100) int antiBruteForceThreshold,
    @JsonKey(name: 'blocklist-enabled') @Default(false) bool blocklistEnabled,
    @JsonKey(name: 'blocklist-size') @Default(0) int blocklistSize,
    @JsonKey(name: 'blocklist-url') @Default('') String blocklistUrl,
    @JsonKey(name: 'cache-size-mb') @Default(4) int cacheSizeMb,
    @JsonKey(name: 'config-dir') @Default('') String configDir,
    @JsonKey(name: 'default-trackers') @Default('') String defaultTrackers,
    @JsonKey(name: 'dht-enabled') @Default(true) bool dhtEnabled,
    @JsonKey(name: 'download-dir') @Default('') String downloadDir,
    @JsonKey(name: 'download-dir-free-space') @Default(0) int downloadDirFreeSpace,
    @JsonKey(name: 'download-queue-enabled') @Default(true) bool downloadQueueEnabled,
    @JsonKey(name: 'download-queue-size') @Default(5) int downloadQueueSize,
    @Default('preferred') String encryption,
    @JsonKey(name: 'idle-seeding-limit') @Default(30) int idleSeedingLimit,
    @JsonKey(name: 'idle-seeding-limit-enabled') @Default(false) bool idleSeedingLimitEnabled,
    @JsonKey(name: 'incomplete-dir') @Default('') String incompleteDir,
    @JsonKey(name: 'incomplete-dir-enabled') @Default(false) bool incompleteDirEnabled,
    @JsonKey(name: 'lpd-enabled') @Default(false) bool lpdEnabled,
    @JsonKey(name: 'peer-limit-global') @Default(200) int peerLimitGlobal,
    @JsonKey(name: 'peer-limit-per-torrent') @Default(50) int peerLimitPerTorrent,
    @JsonKey(name: 'peer-port') @Default(51413) int peerPort,
    @JsonKey(name: 'peer-port-random-on-start') @Default(false) bool peerPortRandomOnStart,
    @JsonKey(name: 'pex-enabled') @Default(true) bool pexEnabled,
    @JsonKey(name: 'port-forwarding-enabled') @Default(true) bool portForwardingEnabled,
    @JsonKey(name: 'queue-stalled-enabled') @Default(true) bool queueStalledEnabled,
    @JsonKey(name: 'queue-stalled-minutes') @Default(30) int queueStalledMinutes,
    @JsonKey(name: 'rename-partial-files') @Default(true) bool renamePartialFiles,
    @JsonKey(name: 'script-torrent-added-enabled') @Default(false) bool scriptTorrentAddedEnabled,
    @JsonKey(name: 'script-torrent-added-filename') @Default('') String scriptTorrentAddedFilename,
    @JsonKey(name: 'script-torrent-done-enabled') @Default(false) bool scriptTorrentDoneEnabled,
    @JsonKey(name: 'script-torrent-done-filename') @Default('') String scriptTorrentDoneFilename,
    @JsonKey(name: 'script-torrent-done-seeding-enabled') @Default(false) bool scriptTorrentDoneSeedingEnabled,
    @JsonKey(name: 'script-torrent-done-seeding-filename') @Default('') String scriptTorrentDoneSeedingFilename,
    @JsonKey(name: 'seed-queue-enabled') @Default(false) bool seedQueueEnabled,
    @JsonKey(name: 'seed-queue-size') @Default(10) int seedQueueSize,
    @JsonKey(name: 'seedRatioLimit') @Default(2.0) double seedRatioLimit,
    @JsonKey(name: 'seedRatioLimited') @Default(false) bool seedRatioLimited,
    @JsonKey(name: 'session-id') @Default('') String sessionId,
    @JsonKey(name: 'speed-limit-down') @Default(100) int speedLimitDown,
    @JsonKey(name: 'speed-limit-down-enabled') @Default(false) bool speedLimitDownEnabled,
    @JsonKey(name: 'speed-limit-up') @Default(100) int speedLimitUp,
    @JsonKey(name: 'speed-limit-up-enabled') @Default(false) bool speedLimitUpEnabled,
    @JsonKey(name: 'start-added-torrents') @Default(true) bool startAddedTorrents,
    @JsonKey(name: 'tcp-enabled') @Default(true) bool tcpEnabled,
    @JsonKey(name: 'trash-original-torrent-files') @Default(false) bool trashOriginalTorrentFiles,
    @JsonKey(name: 'utp-enabled') @Default(false) bool utpEnabled,
  }) = _TransmissionPreferences;

  factory TransmissionPreferences.fromJson(Map<String, dynamic> json) => _$TransmissionPreferencesFromJson(json);
}
